lint:
  nextflow_config:
    - config_defaults:
        - params.bamtools_filter_se_config
        - params.bamtools_filter_pe_config
nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: Espinosa-Carrasco J, Patel H, Wang C, Ewels P
  description: ChIP-seq peak-calling and differential analysis pipeline.
  force: false
  is_nfcore: true
  name: chipseq
  org: nf-core
  outdir: .
  version: 2.2.0dev
